apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xavia-ota-ingress
  namespace: xavia-ota
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"  
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  tls:
  - hosts:
      - "https://ota.your-domain.com"
    secretName: xavia-ota-tls
  rules:
  - host: "https://ota.your-domain.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: xavia-ota-service
            port:
              number: 80